/*
 * Copyright (c) 2020-2025, Sreeni Viswanadha <sreeni@viswanadha.net>.
 * Copyright (c) 2024-2025, Marc Mazas <mazas.marc@gmail.com>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the names of the copyright holders nor the names of its
 *       contributors may be used to endorse or promote products derived from
 *       this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
options
{
//  BUILD_PARSER = false;
//  BUILD_TOKEN_MANAGER = false;
//  JAVA_TEMPLATE_TYPE = "modern";
  DEBUG_LOOKAHEAD = true;
  DEBUG_PARSER = true;
//  DEBUG_TOKEN_MANAGER = true;
//  JAVA_UNICODE_ESCAPE = true;
  KEEP_LINE_COLUMN = true;
  NO_DFA = true;
//  PARSER_INCLUDE = "stdio.h";
//  TOKEN_INCLUDE = "<stdio.h>";
//  TOKEN_MANAGER_INCLUDE = "<stdio.h>";
  SANITY_CHECK = false;
  STATIC = false;

//  NAMESPACE = "mns";
}

PARSER_BEGIN(Bug)
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.io.PrintStream;

public class Bug {
  
  public static void main(String args[]) {
    if (args.length != 3) {
      System.err.println("Error: invalid number of arguments (" + args.length + ")");
      System.err.println("Usage: Bug inputfile outputfile errorfile");
      System.exit(4);
    }
    String fn = null;
    InputStream stdInput  = null;
    PrintStream stdOutput = null;
    PrintStream stdError  = null;
    try {
      // open files and redirect standard streams to them
      fn = "input";
      stdInput = System.in;
      System.setIn(new FileInputStream(args[0]));
      fn = "output";
      stdOutput = System.out;
      System.setOut(new PrintStream(args[1]));
      fn = "error";
      stdError  = System.err;
      System.setErr(new PrintStream(args[2]));
      // parse
      Bug parser = new Bug(System.in);
      parser.EnumerationItem();
      System.err.println("Input file parsed successfully");
    } catch (FileNotFoundException e) {
      System.err.println("FileNotFoundException opening " + fn + " file");
      System.err.println(e.getMessage());
    } catch (ParseException e) {
      System.err.println("ParseException parsing input file");
      System.err.println(e.getMessage());
    } catch (Exception e) {
      System.err.println("Exception parsing input file");
      e.printStackTrace();
    } catch (Error e) {
      System.err.println("Error parsing input file");
      e.printStackTrace();
    } finally {
      // restore standard streams
      if (stdInput  != null) System.setIn(stdInput);
      if (stdOutput != null) System.setOut(stdOutput);
      if (stdError  != null) System.setErr(stdError);
    }
  }
  
}
PARSER_END(Bug)

TOKEN_MGR_DECLS : {
  int my_tm_decl;
}

SKIP : { " " | "\t" | "\n" | "\r" }

TOKEN :
{
  < LBRACKET : "[" >
| < RBRACKET : "]" >
| < LBRACE : "{" >
| < RBRACE : "}" >
| < LPAREN : "(" >
| < RPAREN : ")" >
}

TOKEN :
{
  < #UPPER : ["A"-"Z"] > 
| < #LOWER : ["a"-"z"] > 
| < #DIGIT : ["0"-"9"] > 
| < NUMBER : ( "0" | ["1"-"9"] ( < DIGIT > )*) > 
| < #LOWERCASEFIRST : < LOWER > ( "-" ( < LOWER > | < UPPER > | < DIGIT > ) | ( < LOWER > | < UPPER > | < DIGIT > ) )* > 
| < #UPPERCASEFIRST : < UPPER > ( "-" ( < LOWER > | < UPPER > | < DIGIT > ) | ( < LOWER > | < UPPER > | < DIGIT > ) )* >
}

TOKEN :
{
  < IDENTIFIANT : < LOWERCASEFIRST > >
| < VALUEREFERENCE : < UPPERCASEFIRST > >
}
// special 1, 0 leading spaces; to be copied
/* special 2, 0 leading spaces; to be copied */
/** special 3, 0 leading spaces; to be copied */
void EnumerationItem() :
{}
{
  < LBRACE >
  (
    LOOKAHEAD(2)
    NamedNumber()
  |
    identifier()
  )
  < RBRACE >
}

  // special 4, 2 leading spaces; to be copied; and 5 spaces in the next line
     
     /** special 5, 5 leading spaces; to be copied */
void NamedNumber() :
{}
{
  (
    identifier()
  |
    valuereference()
  )
  < LPAREN > < NUMBER > < RPAREN >
}
// special 6, 0 leading spaces, next to last rbrace, to be copied
void identifier() :
{}
{
  < IDENTIFIANT >
} /* special 7, same line as last rbrace with 1 space, to be copied */

void valuereference() :
{}
{
  < VALUEREFERENCE >
}
