# A comma or space separated list of goals/phases to execute,
# may specify an empty list to execute the default goal of the IT project.
# Environment variables used by maven plugins can be added here

# "normal" install & run goals are defined in ../it/pom.xml;
# may be temporary specifically changed here
#invoker.goals = install run

# may uncomment this for temporary specific debugging
#invoker.debug = true