/*
 * Copyright (c) 2020-2025, Sreeni Viswanadha <sreeni@viswanadha.net>.
 * Copyright (c) 2024-2025, Marc Mazas <mazas.marc@gmail.com>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the names of the copyright holders nor the names of its
 *       contributors may be used to endorse or promote products derived from
 *       this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
options
{
  BUILD_PARSER = false;
  USER_CHAR_STREAM = true;
  DEBUG_TOKEN_MANAGER = true; // (JavaCC - default false)
}

PARSER_BEGIN(CalcInputParser)

public class CalcInputParser {}

PARSER_END(CalcInputParser)

/**
 * This example shows an elaborate example to construct a Finite Automaton,
 * where for every character there is a move.
 */
TOKEN_MGR_DECLS :
{
  /** A pointer to the GUI object. */
  static CalcGUI gui;
  
  /** Holds the current value of the current operand. */
  static double value = 0.0;
  
  /** Holds the result of the expression evaluation so far. */
  static double result = 0.0;
  
  /** Flag to indicate the very first operand so that the correct result is displayed in this case. */
  static boolean firstOperand = true;
  
  private static void setValue()
  {
    dumpInfo();
    value = image.length() > 0 ? Double.valueOf(image.toString()).doubleValue() : 0.0;
    image.setLength(0);
    jjimageLen = 0;
    System.out.println("--> value = " + value + ", firstOperand = " + firstOperand);
  }
  
  private static void showValue()
  {
    System.out.println("==> value = " + value + ", result = " + result + ", firstOperand = " + firstOperand);
    dumpInfo();
    gui.print(value);
  }
  
  /** Shows the result. */
  private static void ShowResult()
  {
    System.out.println("==> result = " + result + ", value = " + value + ", firstOperand = " + firstOperand);
    dumpInfo();
    gui.print(result);
  }
  
  private static void dumpInfo()
  {
    System.out.println(">>> buffer = <" + String.valueOf(((CharCollector) input_stream).buffer) +">");
    System.out.println(">>> lengthOfMatch = " + lengthOfMatch + ", jjmatchedPos = " + jjmatchedPos + ", jjimageLen = " + jjimageLen);
    System.out.println(">>> image = <" + image +">");
    System.out.println(">>> input_stream.GetSuffix(jjimageLen) = <" + String.valueOf(input_stream.GetSuffix(jjimageLen)) +">");
  }
}

/**
 * The first operand
 */
< OPERAND > MORE :
{
  < DIGIT_OPE : ["0" - "9"] > 
  {
    System.out.println("... < OPERAND > MORE : < [0 - 9] >");
    setValue();
  }
| 
  < DOT_OPE : "." >
  : REQUIRED_DIGIT
}

/**
 * This state is entered when we need to get at least one digit (after a .)
 */
< REQUIRED_DIGIT > MORE :
{
  < DIGIT_REQ : ["0" - "9"] >
  {
    System.out.println("... < REQUIRED_DIGIT > MORE : < [0 - 9] >");
    setValue();
  }
  : OPTIONAL_DIGIT
}

/**
 * FA for (["0"-"9"])*.
 */
< OPTIONAL_DIGIT > MORE :
{
  < DIGIT_OPT : ["0" - "9"] >
  {
    System.out.println("... < OPTIONAL_DIGIT > MORE : < [0 - 9] >");
    setValue();
  }
}

/**
 * You can get an operator at any time (in any lexical state), except when a digit is required (after a .).
 * Then just go to a state where the next operand is scanned (for that particular operator).
 */
< OP_OR_OPERAND, OPERAND, OPTIONAL_DIGIT, OP_LOOP > SKIP :
{
  < PLUS : "+" >
  {
    System.out.println("+++ < OP_OR_OPERAND, OPERAND, OPTIONAL_DIGIT, OP_LOOP > SKIP : < + >");
    showValue();
  }
  : SEEN_PLUS 
| 
  < MINUS : "-" >
  { showValue(); }
  : SEEN_MINUS 
| 
  < STAR : "*" >
  { showValue(); }
  : SEEN_STAR 
| 
  < SLASH : "/" >
  { showValue(); }
  : SEEN_SLASH
}

/**
 * If you get a = in any state, just display the current result.
 */
< OPERAND, OPTIONAL_DIGIT, OP_LOOP > SKIP :
//< SEEN_PLUS, ADD_RIGHT_OPERAND, DO_ADD, OPERAND, OPTIONAL_DIGIT, OP_LOOP > SKIP :
{
  < EQ1 : "=" >
  {
    System.out.println("=== < OPERAND, OPTIONAL_DIGIT, OP_LOOP > SKIP : < EQ >");
//    System.out.println("=== < SEEN_PLUS, ADD_RIGHT_OPERAND, DO_ADD, OPERAND, OPTIONAL_DIGIT, OP_LOOP > SKIP : < = >");
    ShowResult();
  }
  : OP_OR_OPERAND
}

/**
 * Here you can either give an operand (to start a new expression)
 * or give an operator that works on the current result.
 */
< OP_OR_OPERAND > SKIP :
{
  < EQ2 : "=" >
  {
    System.out.println("=2= < OP_OR_OPERAND > SKIP : < = >");
    dumpInfo();
  }
}

< OP_OR_OPERAND > MORE :
{
  < DIGIT_OOO : ["0" - "9"] >
  {
    System.out.println("0-9 < OP_OR_OPERAND > MORE : < [0 - 9] >");
    dumpInfo();
    firstOperand = true;
  }
  : OPERAND 
| 
  < DOT_OOO : "." >
  { firstOperand = true; }
  : REQUIRED_DIGIT
}

< SEEN_PLUS, ADD_RIGHT_OPERAND > MORE :
{
  < DIGIT_ADD1 : ["0" - "9"] >
  {
    System.out.println("0-9 < SEEN_PLUS, ADD_RIGHT_OPERAND > MORE : < [0 - 9] >");
    firstOperand = true;
    setValue();
  }
  : ADD_RIGHT_OPERAND 
| 
  < DOT_ADD : "." >
  : ADD_REQUIRED_DIGIT
}

< DO_ADD, ADD_REQUIRED_DIGIT > MORE :
{
  < DIGIT_ADD2 : ["0" - "9"] >
  : DO_ADD
}

< DO_ADD, ADD_RIGHT_OPERAND > SKIP :
{
  < EMPTY_ADD : "" >
  {
    System.out.println("+++. < DO_ADD, ADD_RIGHT_OPERAND > SKIP : < >");
    dumpInfo();
//    result += Double.valueOf(image.toString()).doubleValue();
    result += value;
  }
  : OP_LOOP
}

< SEEN_MINUS, SUB_RIGHT_OPERAND > MORE :
{
  < DIGIT_SUB1 : ["0" - "9"] >
  : SUB_RIGHT_OPERAND 
| 
  < DOT_SUB : "." >
  : SUB_REQUIRED_DIGIT
}

< DO_SUB, SUB_REQUIRED_DIGIT > MORE :
{
  < DIGIT_SUB2 : ["0" - "9"] >
  : DO_SUB
}

< DO_SUB, SUB_RIGHT_OPERAND > SKIP :
{
  < EMPTY_SUB : "" >
  { result -= Double.valueOf(image.toString()).doubleValue(); }
  : OP_LOOP
}

< SEEN_STAR, MUL_RIGHT_OPERAND > MORE :
{
  < DIGIT_MUL1 : ["0" - "9"] >
  : MUL_RIGHT_OPERAND 
| 
  < DOT_MUL : "." >
  : MUL_REQUIRED_DIGIT
}

< DO_MUL, MUL_REQUIRED_DIGIT > MORE :
{
  < DIGIT_MUL2 : ["0" - "9"] >
  : DO_MUL
}

< DO_MUL, MUL_RIGHT_OPERAND > SKIP :
{
  < EMPTY_MUL : "" >
  { result *= Double.valueOf(image.toString()).doubleValue(); }
  : OP_LOOP
}

< SEEN_SLASH, DIV_RIGHT_OPERAND > MORE :
{
  < DIGIT_DIV1 : ["0" - "9"] >
  : DIV_RIGHT_OPERAND 
| 
  < DOT_DIV : "." >
  : DIV_REQUIRED_DIGIT
}

< DO_DIV, DIV_REQUIRED_DIGIT > MORE :
{
  < DIGIT_DIV2 : ["0" - "9"] >
  : DO_DIV
}

< DO_DIV, DIV_RIGHT_OPERAND > SKIP :
{
  < EMPTY_DIV : "" >
  { result /= Double.valueOf(image.toString()).doubleValue(); }
  : OP_LOOP
}
