PARSER_BEGIN(ElementsUsuels2)

/** Une illustration de "regular_expr_production" fréquemment rencontrées. */
public class ElementsUsuels2
{
  public static final void main(String args []) throws ParseException
  {
    ElementsUsuels2 parser = new ElementsUsuels2(System.in);
    parser.ProgramUnit();
  }

  static void dump(Token aT)
  {
    System.out.print("Token type = " + tokenImage [aT.kind] + ", image = " + aT.image);
    System.out.print(", bl = " + aT.beginLine + ", bc = " + aT.beginColumn);
    System.out.print(", el = " + aT.endLine + ", ec = " + aT.endLine + ", special = (<");
    Token st = aT.specialToken;
    while (st != null && st.specialToken != null)
    {
      st = st.specialToken;
    }
    while (st != null)
    {
      System.out.print(tokenImage [st.kind] + ">/<" + st.image + ">)(<");
      st = st.next;
    }
    System.out.println(">)");
  }
}

PARSER_END(ElementsUsuels2)


SKIP :
{
  < SPACE : " " >
| < TAB : "\t" >
| < LF : "\n" >
| < CR : "\r" >
}

SPECIAL_TOKEN :
{
  < LINE_COMMENT : "--" (~[ "\r", "\n" ])* >
}

MORE :
{
  < BEG_SINGLE_LINE_COMMENT : "//" > : IN_SINGLE_LINE_COMMENT
| 
  < BEG_FORMAL_LINE_COMMENT : "/**" ~[ "/" ] >
  {
    input_stream.backup(1);
  }
  : IN_FORMAL_COMMENT
| 
  < BEG_MULTI_LINE_COMMENT : "/*" > : IN_MULTI_LINE_COMMENT
}

< IN_SINGLE_LINE_COMMENT >
SPECIAL_TOKEN :
{
  < END_SINGLE_LINE_COMMENT :
    "\n"
  | "\r"
  | "\r\n" > : DEFAULT
}

< IN_FORMAL_COMMENT >
SPECIAL_TOKEN :
{
  < END_FORMAL_COMMENT : "*/" > : DEFAULT
}

< IN_MULTI_LINE_COMMENT >
SPECIAL_TOKEN :
{
  < END_MULTI_LINE_COMMENT : "*/" > : DEFAULT
}

< IN_SINGLE_LINE_COMMENT, IN_FORMAL_COMMENT, IN_MULTI_LINE_COMMENT >
MORE :
{
  < MORE_CHAR_IN_COMMENT : ~[ ] >
}

TOKEN :
{
  < #LETTER : [ "a"-"z", "A"-"Z", "_" ] >
| 
  < #DIGIT : [ "0"-"9" ] >
| 
  < NUM : (< DIGIT >)+ >
| 
  < CHARACTER_LITERAL :
    "'"
    (
      (~[ "'", "\\", "\n", "\r" ])
    |
      (
        "\\"
        (
          [ "n", "t", "b", "r", "f", "\\", "'", "\"" ]
        | [ "0"-"7" ] ([ "0"-"7" ])?
        | [ "0"-"3" ] [ "0"-"7" ] [ "0"-"7" ]
        )
      )
    )
    "'" 
  >
| 
  < STRING_LITERAL :
    "\""
    (
      (~[ "\"", "\\", "\n", "\r" ])
    |
      (
        "\\"
        (
          [ "n", "t", "b", "r", "f", "\\", "'", "\"" ]
        | [ "0"-"7" ] ([ "0"-"7" ])?
        | [ "0"-"3" ] [ "0"-"7" ] [ "0"-"7" ]
        )
      )
    )*
    "\"" 
  >
| 
  < ID :
    < LETTER >
    (
      < LETTER >
    | < NUM >
    )* >
}

void ProgramUnit() :
{
  Token t;
}
{
  (
    (
      t = < ID >
    | t = < NUM >
    | t = < CHARACTER_LITERAL >
    | t = < STRING_LITERAL >
    )
    {
      dump(t);
    }
  )+
  < EOF >
}
