/*
 * Copyright (c) 2020-2025, Sreeni Viswanadha <sreeni@viswanadha.net>.
 * Copyright (c) 2024-2025, Marc Mazas <mazas.marc@gmail.com>.
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Sun Microsystems, Inc. nor the names of its
 *       contributors may be used to endorse or promote products derived from
 *       this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
options {
  STATIC = false; // not JavaCC's default; not the same as Faq
}

PARSER_BEGIN(Digest)
package dig; // different from Faq, to allow different helper files

import java.io.*;

public class Digest {
  private int count = 0;
  PrintWriter digpw;

public void setDigpw(final PrintWriter aDigpw) {
    digpw = aDigpw;
  }
}

PARSER_END(Digest)

String MailFile() :
{
  String mail, mails = "";
}
{
  (
    { count++; }
    mail = MailMessage()
    {
      mails += mail;
      System.out.print(count + ".");
      System.out.flush();
    }
  )*
  <EOF>
  {
    System.out.println("");
    return mails;
  }
}

String MailMessage() :
{
  Token subj = null, from = null, date = null, body;
  String buffer = "";
}
{
  ( subj = <SUBJECT> | from = <FROM> | date = <DATE> )+
  {
    digpw.println(count + ". " + ( subj == null ? "no subject" : subj.image) );
    buffer += "\n";
    buffer += "Message " + count + ":\n";
    buffer += "\n";
    buffer += "Subject: " + (subj == null ? "no subject" : subj.image) + "\n";
    buffer += "From: " + (from == null ? "" : from.image) + "\n";
    buffer += "Date: " + (date == null ? "" : date.image) + "\n";
    buffer += "\n";
  }
  (
    body = <BODY>
    {
      buffer += body.image;
    }
  )*
  <END>
  {
    buffer += "\n";
    buffer += "----------------------------------------------------------------------\n";
    return buffer;
  }
}

TOKEN :
{
  < #EOL : "\n" | "\r" | "\r\n" >
|
  < #TWOEOLS : ( ( "\n" | "\r\n" ) <EOL>) | ( "\r\r" [ "\n" ] )>
|
  < #NOT_EOL : ~[ "\n", "\r" ] >
}

<DEFAULT>
SKIP :
{
  < <EOL> "*** EOOH ***" <EOL> > : MAILHEADER
|
  <~[]>
}

<MAILHEADER>
SKIP :
{
  < _TWOEOLS : <TWOEOLS> > : MAILBODY
    // We cannot have just a reference to a regular expression in a
    // lexical specification - i.e., we cannot simply have <TWOEOLS>.
|
  "Subject: " : MAILSUBJECT
|
  "From: " : MAILFROM
|
  "Date: " : MAILDATE
|
  <~[]>
}

<MAILSUBJECT>
TOKEN :
{
  < SUBJECT : ( <NOT_EOL> )+ >
}

<MAILSUBJECT>
SKIP :
{
  < _EOL1 : <EOL> > : MAILHEADER
}

<MAILFROM>
TOKEN :
{
  < FROM : ( <NOT_EOL> )+ >
}

<MAILFROM>
SKIP:
{
  < _EOL2 : <EOL> > : MAILHEADER
}

<MAILDATE>
TOKEN:
{
  < DATE : ( <NOT_EOL> )+ >
}

<MAILDATE>
SKIP :
{
  < _EOL3 : <EOL> > : MAILHEADER
}

<MAILBODY>
TOKEN :
{
  < BODY : ( ~["\n", "\r", "\u001f" ] )* <EOL> >
| 
  < END : "\u001f" > : DEFAULT
}
