<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright (c) 2020-2025, Sreeni Viswanadha <sreeni@viswanadha.net>.
Copyright (c) 2024-2025, Marc Mazas <mazas.marc@gmail.com>.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
      this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the names of the copyright holders nor the names of its
      contributors may be used to endorse or promote products derived from
      this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
THE POSSIBILITY OF SUCH DAMAGE.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.javacc.generator.java</groupId>
    <artifactId>examples</artifactId>
    <version>1.1.0-SNAPSHOT</version>
  </parent>

  <groupId>org.javacc.generator.java.examples</groupId>
  <artifactId>CustomTemplate</artifactId>
  <packaging>jar</packaging>

  <name>JavaCC Java code generator / CustomTemplate</name>

  <!-- just generate parser and see customization outcome  -->
  <build>
    <plugins>

      <plugin>
        <!-- during the initialize phase: -->
        <!-- (re)create the target custom directory (by copying an existing file)
              (otherwise the next jar command will fail) -->
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <executions>
          <execution>
            <id>custom-dir</id>
            <phase>initialize</phase>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <configuration>
              <outputDirectory>${basedir}/target/custom</outputDirectory>
              <resources>
                <resource>
                  <directory>${basedir}/src/main/custom</directory>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <!-- during the initialize phase: -->
        <!-- builds a jar file from the source custom directory in the target custom directory
              (keeping the resource path starting with /templates/java) -->
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>jar-cust-jar</id>
            <phase>initialize</phase>
            <goals>
              <goal>exec</goal>
            </goals>
            <configuration>
              <executable>jar</executable>
              <arguments>
                <argument>-c</argument>
                <argument>-f</argument>
                <argument>${basedir}/target/custom/cust-tpt.jar</argument>
                <argument>-C</argument>
                <argument>${basedir}/src/main/custom</argument>
                <argument>templates/java</argument>
              </arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <!-- during the initialize phase: -->
        <!-- install the custom jar file in the local repository -->
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-install-plugin</artifactId>
        <executions>
          <execution>
            <id>install-cust-file</id>
            <phase>initialize</phase>
            <goals>
              <goal>install-file</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <file>${basedir}/target/custom/cust-tpt.jar</file>
          <groupId>org.javacc.generator.java.examples.CustomTemplate</groupId>
          <artifactId>custom-jar</artifactId>
          <version>1.1.0-SNAPSHOT</version>
          <packaging>jar</packaging>
        </configuration>
      </plugin>

      <plugin>
        <!-- now in the normal process-resources phase: -->
        <!-- add the custom jar in the dependencies
             (by chance this keeps the dependencies already set in the parent) -->
        <groupId>org.javacc.plugin</groupId>
        <artifactId>javacc-maven-plugin</artifactId>
        <dependencies>
          <dependency>
            <groupId>org.javacc.generator.java.examples.CustomTemplate</groupId>
            <artifactId>custom-jar</artifactId>
            <version>1.1.0-SNAPSHOT</version>
            <scope>runtime</scope>
          </dependency>
        </dependencies>
      </plugin>

    </plugins>

  </build>

</project>