/*
 * Copyright (c) 2020-2025, Sreeni Viswanadha <sreeni@viswanadha.net>.
 * Copyright (c) 2024-2025, Marc Mazas <mazas.marc@gmail.com>.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *     * Redistributions of source code must retain the above copyright notice,
 *       this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the names of the copyright holders nor the names of its
 *       contributors may be used to endorse or promote products derived from
 *       this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
 * THE POSSIBILITY OF SUCH DAMAGE.
 */
package org.javacc.java;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.javacc.Version;
import org.javacc.parser.CodeGeneratorSettings;
import org.javacc.parser.Context;
import org.javacc.parser.JavaCCGlobals;
import org.javacc.parser.MetaParseException;
import org.javacc.parser.Options;
import org.javacc.parser.RStringLiteral;
import org.javacc.parser.RegExprSpec;
import org.javacc.parser.RegularExpression;
import org.javacc.parser.TokenProduction;
import org.javacc.parser.TokenizerData;

/** The {@link JavaHelperFiles} class. */
abstract class JavaHelperFiles {

  /** Constructs an instance of {@link JavaHelperFiles}. */
  private JavaHelperFiles() {}

  static void genMiscFile(final String fileName, final String templatePath, final Context context)
      throws Error {
    try (JavaCodeBuilder jcb =
        JavaCodeBuilder.of(context, CodeGeneratorSettings.of(Options.getOptions()))) {
      jcb.setFile(new File(Options.getOutputDirectory(), fileName));
      jcb.setVersion(Version.version)
          //          .addOption(Options.UO__KEEP_LINE_COLUMN)
          .addTools(JavaCCGlobals.toolName);
      jcb.setPackageName(JavaUtil.parsePackage(context));
      jcb.printTemplate(templatePath);
    } catch (final IOException e) {
      System.err.println("Failed to create " + fileName + " " + e);
      context.errors().semantic_error("Could not open file " + fileName + " for writing.");
      throw new Error();
    }
  }

  static void gen_TokenManager(final Context context) {
    try (JavaCodeBuilder jcb =
        JavaCodeBuilder.of(context, CodeGeneratorSettings.of(Options.getOptions()))) {
      jcb.setFile(new File(Options.getOutputDirectory(), "TokenManager.java"));
      jcb.setVersion(Version.version)
          .addTools(JavaCCGlobals.toolName)
          .addOption(Options.UO__SUPPORT_CLASS_VISIBILITY_PUBLIC);
      jcb.setPackageName(JavaUtil.parsePackage(context));
      jcb.printTemplate("/templates/java/TokenManager.template");
    } catch (final IOException e) {
      System.err.println("Failed to create TokenManager " + e);
      context.errors().semantic_error("Could not open file TokenManager.java for writing.");
      throw new Error();
    }
  }

  static void gen_Constants(final Context context, final TokenizerData tokenizerData)
      throws MetaParseException {
    if (context.errors().get_error_count() != 0) {
      throw new MetaParseException();
    }

    final List<String> toolnames = new ArrayList<>(context.globals().toolNames);
    toolnames.add(JavaCCGlobals.toolName);

    try (JavaCodeBuilder jcb = JavaCodeBuilder.of(context, CodeGeneratorSettings.create())) {
      jcb.setFile(
          new File(Options.getOutputDirectory(), context.globals().cu_name + "Constants.java"));
      jcb.setPackageName(JavaUtil.parsePackage(context));
      jcb.addTools(toolnames.toArray(new String[toolnames.size()]));

      jcb.println("/**");
      jcb.println(" * Token literal values and constants.");
      jcb.println(" * Generated by JavaHelperFiles#gen_Constants()");
      jcb.println(" */");

      if (Options.getSupportClassVisibilityPublic()) {
        jcb.print("public ");
      }
      jcb.println("interface " + context.globals().cu_name + "Constants {");
      jcb.println();

      jcb.println("  /** Token kind 0. */");
      jcb.println("  int EOF = 0;");
      for (final RegularExpression re : context.globals().ordered_named_tokens) {
        jcb.println("  /** Labeled token " + re.ordinal + " kind. */");
        jcb.println("  int " + re.label + " = " + re.ordinal + ";");
      }
      jcb.println();
      if (!Options.getUserTokenManager() && Options.getBuildTokenManager()) {
        for (int i = 0; i < tokenizerData.lexStateNames.length; i++) {
          jcb.println("  /** Lexical state " + i + ". */");
          jcb.println("  int " + tokenizerData.lexStateNames[i] + " = " + i + ";");
        }
        jcb.println();
        jcb.println("  /** Lexical state names. */");
        jcb.println("  public static String[] lexStateNames = {");
        for (int i = 0; i < tokenizerData.lexStateNames.length; i++) {
          if (i > 0) {
            jcb.println(",");
          }
          jcb.print("    \"" + tokenizerData.lexStateNames[i] + "\"");
        }
        jcb.println();
        jcb.println("  };");
        jcb.println();
      }

      jcb.println("  /**");
      jcb.println("   * Tokens labels (if any) or images (if string literal) or named kinds<br>");
      jcb.println("   * (for non labeled non string literals).");
      jcb.println("   */");
      jcb.println("  String[] tokenImage = {");
      jcb.println("    \"<EOF>\",");
      for (final TokenProduction tp : context.globals().rexprlist) {
        for (final RegExprSpec res : tp.respecs) {
          jcb.print("    ");
          if (!res.rexp.label.equals("")) {
            jcb.println("\"<" + res.rexp.label + ">\",");
          } else if (res.rexp instanceof RStringLiteral) {
            jcb.println(
                "\"\\\""
                    + JavaCCGlobals.add_escapes(
                        JavaCCGlobals.add_escapes(((RStringLiteral) res.rexp).image))
                    + "\\\"\",");
          } else {
            if (res.rexp.tpContext.kind == TokenProduction.TOKEN) {
              context
                  .errors()
                  .warning(
                      res.rexp,
                      "Consider giving this (non string literal) token a label for better error reporting.");
            }
            jcb.println("\"<token of kind " + res.rexp.ordinal + ">\",");
          }
        }
      }
      jcb.println("  };");
      jcb.println("}");
      jcb.println();

    } catch (final java.io.IOException e) {
      context
          .errors()
          .semantic_error(
              "Could not open file " + context.globals().cu_name + "Constants.java for writing.");
      throw new Error();
    }
  }

  static void generateSimple(
      final String template,
      final String outputFileName,
      final CodeGeneratorSettings settings,
      final Context context)
      throws IOException {
    final File file = new File((String) settings.get("OUTPUT_DIRECTORY"), outputFileName);

    try (JavaCodeBuilder jcb = JavaCodeBuilder.of(context, settings)) {
      jcb.setFile(file);
      jcb.setPackageName(JavaUtil.parsePackage(context));
      jcb.printTemplate(template);
    }
  }
}
